# Site settings
title: Yaakov Su
name: Yaakov Su # your name
email: yhsu1024@163.com # your email address
description: >
    A Simple Jekyll Blog Theme. # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
fileurl: "/YaakovSu.github.io"
url: "https://yaakovary.com" # the base hostname & protocol for your site
twitter_username: doG__uS # your Twitter username
github_username: YaakovSu # your Github username
disqus_username: yaakovsu # your disqus username

google-analytics: UA-76674098-1 # add it if you have one

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
